name: Transpile and Deploy to mirrored Host
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # Set up Node.js to use Babel for transpiling index.js for legacy PS4 WebKit compatibility
      - name: Set up Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Transpile index.js for legacy PS4 WebKit
        run: npm run build

      - name: Upload to mirrored host via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./   # folder you want to upload
          server-dir: /webkitty.free.nf/   # your web root
          exclude: |
            **/.git*
            **/node_modules/**
